import numpy as np

class LezowskiKernel:
    def __init__(self, data_file="field_data.txt"):
        self.degree = 0
        self.r1 = 0
        self.r2 = 0
        self.basis_embeddings = []  # List of arrays representing generators
        self.units_embeddings = []  # List of arrays representing fundamental units
        self.parse_data_file(data_file)
        
    def parse_data_file(self, filename):
        with open(filename, 'r') as f:
            lines = f.readlines()
            
        idx = 0
        while idx < len(lines):
            line = lines[idx].strip()
            if not line or line.startswith("#"):
                idx += 1
                continue
                
            if line.startswith("degree:"):
                self.degree = int(line.split(":")[1].strip())
            elif line.startswith("r1:"):
                self.r1 = int(line.split(":")[1].strip())
            elif line.startswith("r2:"):
                self.r2 = int(line.split(":")[1].strip())
                
            elif line.startswith("INTEGRAL_BASIS_EMBEDDINGS:"):
                idx += 1
                for _ in range(self.degree):
                    # Skip generator header comments if any
                    while lines[idx].strip().startswith("#") or not lines[idx].strip():
                        idx += 1
                    
                    # Read r1 + r2 rows for this generator
                    gen_rows = []
                    for _ in range(self.r1 + self.r2):
                        row_data = list(map(float, lines[idx].strip().split()))
                        # Convert to complex numbers: real + j * imag
                        gen_rows.append(complex(row_data[0], row_data[1]))
                        idx += 1
                    self.basis_embeddings.append(np.array(gen_rows))
                continue
                
            elif line.startswith("FUNDAMENTAL_UNITS_COUNT:"):
                num_units = int(line.split(":")[1].strip())
                idx += 1
                for _ in range(num_units):
                    while idx < len(lines) and not lines[idx].strip().startswith("UNIT_"):
                        idx += 1
                    if idx >= len(lines): break
                    idx += 1 # skip unit header line
                    
                    unit_rows = []
                    for _ in range(self.r1 + self.r2):
                        row_data = list(map(float, lines[idx].strip().split()))
                        unit_rows.append(complex(row_data[0], row_data[1]))
                        idx += 1
                    self.units_embeddings.append(np.array(unit_rows))
                continue
                
            idx += 1
            
        # Convert lists to solid matrix wrappers for vectorization
        self.basis_matrix = np.column_stack(self.basis_embeddings) # Matrix size: (r1+r2) x degree

    def compute_element_embeddings(self, coefficients):
        """
        Given abstract integer/fractional coordinates relative to the integral basis,
        map them into their actual mixed space embeddings.
        """
        # coefficients is a vector of length 'degree' (e.g. [0.5, 0.5, 0.0])
        return np.dot(self.basis_matrix, coefficients)

    def calculate_norm(self, embeddings_vector):
        """
        Calculates Lezowski's generalized absolute field norm for signature (r1, r2)
        """
        norm = 1.0
        # 1. Product of real embeddings
        for i in range(self.r1):
            norm *= abs(embeddings_vector[i].real)
            
        # 2. Product of square modules of complex embeddings
        for j in range(self.r2):
            c_val = embeddings_vector[self.r1 + j]
            norm *= (c_val.real**2 + c_val.imag**2) # Absolute square |z|^2
            
        return norm

    def test_box_covering(self, box_center, target_bound=1.0):
        """
        Core Kernel Routine: Evaluates if the geometric box center yields 
        a remainder lower than the target bound when subtracted from the nearest integer.
        """
        # 1. Get raw geometry coordinates
        emb = self.compute_element_embeddings(box_center)
        
        # 2. Evaluate algebraic distance from origin (or test shifts by elements of O_K)
        norm = self.calculate_norm(emb)
        if norm < target_bound:
            return True # Covered by 0
            
        # 3. Apply Fundamental Unit action shifts to compress the geometric coordinates
        for unit in self.units_embeddings:
            # Shift via coordinate multiplication in mixed space
            shifted_emb = emb * unit 
            if self.calculate_norm(shifted_emb) < target_bound:
                return True
                
        return False

# Quick Example Run:
if __name__ == "__main__":
    # Assumes field_data.txt generated by your Pari/GP script is in the directory
    try:
        kernel = LezowskiKernel("field_data.txt")
        print(f"Loaded field with degree {kernel.degree} and signature ({kernel.r1}, {kernel.r2})")
        
        # Test a fractional point in the space (e.g., [1/2, 1/2, 1/2])
        test_coord = [0.5, 0.5, 0.5]
        is_covered = kernel.test_box_covering(test_coord, target_bound=1.0)
        print(f"Is coordinate {test_coord} covered below norm bound 1.0? -> {is_covered}")
        
    except FileNotFoundError:
        print("Please place the 'field_data.txt' file in this running directory.")
